version: "3.9"

services:

  ollama:
    image: ollama/ollama:latest
    hostname: ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    ports:
      - "11434:11434"
    expose:
      - 11434
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    volumes:
      - ./ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

#- driver: nvidia
#  count: all
#  capabilities: [ gpu ]